name: CI
'on':
  push:
    branches:
      - main
jobs:
  full-tests:
    name: Full Tests
    runs-on: ubuntu-latest
    env:
      MIX_ENV: test
    steps:
      - uses: actions/checkout@v3
      - name: Cache deps
        id: cache-deps
        uses: actions/cache@v3
        env:
          cache-name: cache-elixir-deps
        with:
          path: deps
          key: >-
            ${{ runner.os }}-mix-${{ env.MIX_ENV }}-${{ env.cache-name }}-${{
            hashFiles('**/mix.lock') }}
          restore-keys: |
            ${{ runner.os }}-mix-${{ env.MIX_ENV }}-${{ env.cache-name }}-
      - name: Cache compiled build
        id: cache-build
        uses: actions/cache@v3
        env:
          cache-name: cache-compiled-build
        with:
          path: _build
          key: >-
            ${{ runner.os }}-mix-${{ env.MIX_ENV }}-${{ env.cache-name }}--${{
            hashFiles('**/mix.lock') }}
          restore-keys: |
            ${{ runner.os }}-mix-${{ env.MIX_ENV }}-${{ env.cache-name }}-
            ${{ runner.os }}-mix-${{ env.MIX_ENV }}-
            ${{ runner.os }}-mix
      - name: Set up Elixir
        uses: erlef/setup-beam@v1
        with:
          elixir-version: 1.15.7
          otp-version: 26.1.2
      - name: Install dependencies
        run: mix deps.get
      - name: Run format check
        run: mix format --check-formatted
      - name: Start SurrealDB docker image
        run: dev/ci-docker-surreal-restart.sh
      - name: Mix test
        run: mix test
      - name: Stop SurrealDB docker image
        run: dev/ci-docker-surreal-stop.sh
